const ActionTypes ={
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_ACCESS_TOKEN : "SET_ACCESS_TOKEN",
    TOKEN_EXPIRED:"TOKEN_EXPIRED",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    GET_DISCOVER_WEEKLY: "GET_DISCOVER_WEEKLY"
};

export default ActionTypes;